# Generated by Django 6.0.7 on 2026-07-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_firstname_alter_customuser_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
    ]
