# Generated by Django 6.0.7 on 2026-07-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit amount (Add funds)'), ('Order_Payment', 'Malipo ya Oda (SMM/SMS/PHONENUMBER)')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiasi (TSh)')),
                ('description', models.TextField(blank=True, null=True)),
                ('stutus', models.CharField(choices=[('Pending', 'Inasubiri'), ('Success', 'Imekamilika'), ('Failed', 'Imefeli')], default='Sucess', max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userwallet')),
            ],
        ),
    ]
